export const SIGNING_IN_USER = "SIGNING_IN_USER";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAILED = "SIGN_IN_USER_FAILED";
export const SIGNING_UP_USER = "SIGNING_UP_USER";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_UP_USER_FAILED = "SIGN_UP_USER_FAILED";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCESS";
export const FETCHING_ACCOUNT_DATA = "FETCHING_ACCOUNT_DATA";
export const FETCH_ACCOUNT_DATA_SUCCESS = "FETCH_ACCOUNT_DATA_SUCCESS";
export const FETCH_ACCOUNT_DATA_FAILED = "FETCH_ACCOUNT_DATA_FAILED";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const UPDATING_USER_DATA = "UPDATING_USER_DATA";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILED = "UPDATE_USER_DATA_FAILED";
export const BLOCKING_CONTACT = "BLOCKING_CONTACT";
export const BLOCK_CONTACT_SUCCESS = "BLOCK_CONTACT_SUCCESS";
export const BLOCK_CONTACT_FAILED = "BLOCK_CONTACT_FAILED";
export const UNBLOCKING_CONTACT = "UNBLOCKING_CONTACT";
export const UNBLOCK_CONTACT_SUCCESS = "UNBLOCK_CONTACT_SUCCESS";
export const UNBLOCK_CONTACT_FAILED = "UNBLOCK_CONTACT_FAILED";
export const UPDATE_USER_PRIVACY_SETTINGS_SUCCESS =
  "UPDATE_USER_PRIVACY_SETTINGS_SUCCESS";
export const UPDATE_USER_PRIVACY_SETTINGS_FAILED =
  "UPDATE_USER_PRIVACY_SETTINGS_FAILED";
export const USER_DATA_IS_UPDATED = "USER_DATA_IS_UPDATED";
